version: '2'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:10
    volumes:
      - postgresql_data:/postgresql
    environment:
      - POSTGRESQL_DATABASE=airflow
      - POSTGRESQL_USERNAME=airflow
      - POSTGRESQL_PASSWORD=airflow
      - ALLOW_EMPTY_PASSWORD=yes
  airflow:
    image: docker.io/bitnami/airflow:2
    environment:
      - AIRFLOW_DATABASE_NAME=airflow
      - AIRFLOW_DATABASE_USERNAME=airflow
      - AIRFLOW_DATABASE_PASSWORD=airflow
      - AIRFLOW_EXECUTOR=LocalExecutor
      - AIRFLOW_LOAD_EXAMPLES=no
      - AIRFLOW_PASSWORD=airflow
      - AIRFLOW_USERNAME=airflow
#      - AIRFLOW_POOL_NAME=airflow_pool
#      - AIRFLOW_POOL_SIZE=4
    ports:
      - '8080:8080'
    volumes:
      - airflow_data:/airflow

volumes:
  airflow_data:
    driver: local
  postgresql_data:
    driver: local
