version: '2'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:10
    volumes:
      - postgresql_data:/postgresql
    environment:
      - POSTGRESQL_DATABASE=postgres
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - ALLOW_EMPTY_PASSWORD=yes
  airflow:
    image: docker.io/bitnami/airflow:2
    environment:
      - AIRFLOW_DATABASE_NAME=postgres
      - AIRFLOW_DATABASE_USERNAME=postgres
      - AIRFLOW_DATABASE_PASSWORD=postgres
      - AIRFLOW_EXECUTOR=LocalExecutor
      - AIRFLOW_LOAD_EXAMPLES=no
      - AIRFLOW_PASSWORD=airflow
      - AIRFLOW_USERNAME=airflow
    ports:
      - 8080:8080
    volumes:
      - airflow_data:/airflow

volumes:
  airflow_data:
    driver: local
  postgresql_data:
    driver: local
